<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Location;
use App\Models\Client;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = Client::all();

        if ($clients->isEmpty()) {
            $this->command->info('No clients found. Please run ClientSeeder first.');
            return;
        }

        $locations = [
            [
                'client_id' => $clients->first()->id,
                'nickname' => 'Main Pool',
                'street_address' => '123 Main Street',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'zip_code' => '85001',
                'access' => 'residential',
                'pool_type' => 'concrete',
                'water_type' => 'chlorine',
                'filter_type' => 'Sand Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 25000,
                'service_frequency' => 'weekly',
                'service_day_1' => 'Monday',
                'rate_per_visit' => 85.00,
                'chemicals_included' => true,
                'is_favorite' => true,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->first()->id,
                'nickname' => 'Backyard Oasis',
                'street_address' => '456 Oak Avenue',
                'street_address_2' => 'Unit 2B',
                'city' => 'Scottsdale',
                'state' => 'AZ',
                'zip_code' => '85250',
                'access' => 'residential',
                'pool_type' => 'fiberglass',
                'water_type' => 'salt',
                'filter_type' => 'Cartridge Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 18000,
                'service_frequency' => 'bi_weekly',
                'service_day_1' => 'Wednesday',
                'rate_per_visit' => 75.00,
                'chemicals_included' => true,
                'is_favorite' => false,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(1)->first()->id,
                'nickname' => 'Community Pool',
                'street_address' => '789 Pine Road',
                'city' => 'Tempe',
                'state' => 'AZ',
                'zip_code' => '85281',
                'access' => 'commercial',
                'pool_type' => 'concrete',
                'water_type' => 'chlorine',
                'filter_type' => 'DE Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 50000,
                'service_frequency' => 'semi_weekly',
                'service_day_1' => 'Monday',
                'service_day_2' => 'Thursday',
                'rate_per_visit' => 120.00,
                'chemicals_included' => true,
                'is_favorite' => true,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(2)->first()->id,
                'nickname' => 'Family Pool',
                'street_address' => '321 Elm Street',
                'city' => 'Mesa',
                'state' => 'AZ',
                'zip_code' => '85201',
                'access' => 'residential',
                'pool_type' => 'vinyl_liner',
                'water_type' => 'salt',
                'filter_type' => 'Sand Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 22000,
                'service_frequency' => 'weekly',
                'service_day_1' => 'Tuesday',
                'rate_per_visit' => 80.00,
                'chemicals_included' => true,
                'is_favorite' => false,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(3)->first()->id,
                'nickname' => 'Hotel Pool',
                'street_address' => '654 Maple Drive',
                'city' => 'Gilbert',
                'state' => 'AZ',
                'zip_code' => '85233',
                'access' => 'commercial',
                'pool_type' => 'concrete',
                'water_type' => 'chlorine',
                'filter_type' => 'Cartridge Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 75000,
                'service_frequency' => 'semi_weekly',
                'service_day_1' => 'Monday',
                'service_day_2' => 'Thursday',
                'rate_per_visit' => 150.00,
                'chemicals_included' => true,
                'is_favorite' => true,
                'status' => 'inactive',
            ],
            [
                'client_id' => $clients->skip(4)->first()->id,
                'nickname' => 'Spa Pool',
                'street_address' => '987 Cedar Lane',
                'city' => 'Chandler',
                'state' => 'AZ',
                'zip_code' => '85224',
                'access' => 'residential',
                'pool_type' => 'fiberglass',
                'water_type' => 'salt',
                'filter_type' => 'Cartridge Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 15000,
                'service_frequency' => 'weekly',
                'service_day_1' => 'Friday',
                'rate_per_visit' => 70.00,
                'chemicals_included' => false,
                'is_favorite' => false,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(5)->first()->id,
                'nickname' => 'Resort Pool 1',
                'street_address' => '147 Birch Court',
                'city' => 'Peoria',
                'state' => 'AZ',
                'zip_code' => '85345',
                'access' => 'commercial',
                'pool_type' => 'concrete',
                'water_type' => 'chlorine',
                'filter_type' => 'DE Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 100000,
                'service_frequency' => 'semi_weekly',
                'service_day_1' => 'Monday',
                'service_day_2' => 'Thursday',
                'rate_per_visit' => 200.00,
                'chemicals_included' => true,
                'is_favorite' => true,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(6)->first()->id,
                'nickname' => 'Resort Pool 2',
                'street_address' => '147 Birch Court',
                'city' => 'Peoria',
                'state' => 'AZ',
                'zip_code' => '85345',
                'access' => 'commercial',
                'pool_type' => 'concrete',
                'water_type' => 'chlorine',
                'filter_type' => 'DE Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 80000,
                'service_frequency' => 'semi_weekly',
                'service_day_1' => 'Tuesday',
                'service_day_2' => 'Friday',
                'rate_per_visit' => 180.00,
                'chemicals_included' => true,
                'is_favorite' => false,
                'status' => 'active',
            ],
            [
                'client_id' => $clients->skip(7)->first()->id,
                'nickname' => 'Home Pool',
                'street_address' => '258 Spruce Way',
                'city' => 'Surprise',
                'state' => 'AZ',
                'zip_code' => '85374',
                'access' => 'residential',
                'pool_type' => 'vinyl_liner',
                'water_type' => 'chlorine',
                'filter_type' => 'Sand Filter',
                'setting' => 'outdoor',
                'installation' => 'inground',
                'gallons' => 20000,
                'service_frequency' => 'weekly',
                'service_day_1' => 'Wednesday',
                'rate_per_visit' => 75.00,
                'chemicals_included' => true,
                'is_favorite' => false,
                'status' => 'active',
            ],
        ];

        foreach ($locations as $locationData) {
            Location::create($locationData);
        }

        $this->command->info('Sample locations created successfully!');
    }
} 