<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Report;
use App\Models\Client;
use App\Models\Location;
use App\Models\User;
use Carbon\Carbon;

class ReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = Client::where('is_active', true)->get();
        $locations = Location::where('status', 'active')->get();
        $technicians = User::where('role', 'technician')->where('is_active', true)->get();

        if ($clients->isEmpty() || $locations->isEmpty() || $technicians->isEmpty()) {
            $this->command->info('Skipping report seeding - no clients, locations, or technicians found.');
            return;
        }

        $reportData = [
            [
                'client_id' => $clients->first()->id,
                'location_id' => $locations->first()->id,
                'technician_id' => $technicians->first()->id,
                'service_date' => Carbon::now()->subDays(7),
                'service_time' => '10:00:00',
                'pool_gallons' => 25000,
                'fac' => 2.5,
                'cc' => 0.0,
                'ph' => 7.4,
                'alkalinity' => 120,
                'calcium' => 250,
                'salt' => null,
                'cya' => 50,
                'tds' => 800,
                'vacuumed' => true,
                'brushed' => true,
                'skimmed' => true,
                'cleaned_skimmer_basket' => true,
                'cleaned_pump_basket' => false,
                'cleaned_pool_deck' => true,
                'cleaned_filter_cartridge' => false,
                'backwashed_sand_filter' => false,
                'adjusted_water_level' => true,
                'adjusted_auto_fill' => false,
                'adjusted_pump_timer' => false,
                'adjusted_heater' => false,
                'checked_cover' => false,
                'checked_lights' => true,
                'checked_fountain' => false,
                'checked_heater' => false,
                'chemicals_used' => ['chlorine' => '2 lbs', 'shock' => '1 lb'],
                'chemicals_cost' => 25.00,
                'other_services' => [],
                'other_services_cost' => 0.00,
                'total_cost' => 25.00,
                'notes_to_client' => 'Pool chemistry balanced. Water is clear and clean. No issues found.',
                'notes_to_admin' => 'Standard weekly service completed successfully.',
            ],
            [
                'client_id' => $clients->count() > 1 ? $clients[1]->id : $clients->first()->id,
                'location_id' => $locations->count() > 1 ? $locations[1]->id : $locations->first()->id,
                'technician_id' => $technicians->count() > 1 ? $technicians[1]->id : $technicians->first()->id,
                'service_date' => Carbon::now()->subDays(14),
                'service_time' => '11:30:00',
                'pool_gallons' => 18000,
                'fac' => 1.8,
                'cc' => 0.2,
                'ph' => 7.2,
                'alkalinity' => 110,
                'calcium' => 220,
                'salt' => 3200,
                'cya' => 60,
                'tds' => 1200,
                'vacuumed' => true,
                'brushed' => true,
                'skimmed' => true,
                'cleaned_skimmer_basket' => true,
                'cleaned_pump_basket' => true,
                'cleaned_pool_deck' => false,
                'cleaned_filter_cartridge' => true,
                'backwashed_sand_filter' => false,
                'adjusted_water_level' => true,
                'adjusted_auto_fill' => true,
                'adjusted_pump_timer' => false,
                'adjusted_heater' => false,
                'checked_cover' => false,
                'checked_lights' => false,
                'checked_fountain' => true,
                'checked_heater' => false,
                'chemicals_used' => ['salt' => '5 lbs', 'stabilizer' => '2 lbs'],
                'chemicals_cost' => 35.00,
                'other_services' => ['filter_cleaning' => 'Filter cartridge replaced'],
                'other_services_cost' => 15.00,
                'total_cost' => 50.00,
                'notes_to_client' => 'Salt levels adjusted. Filter cartridge cleaned and replaced. Pool is in excellent condition.',
                'notes_to_admin' => 'Saltwater pool maintenance completed. Filter replacement needed.',
            ],
            [
                'client_id' => $clients->count() > 2 ? $clients[2]->id : $clients->first()->id,
                'location_id' => $locations->count() > 2 ? $locations[2]->id : $locations->first()->id,
                'technician_id' => $technicians->count() > 2 ? $technicians[2]->id : $technicians->first()->id,
                'service_date' => Carbon::now()->subDays(21),
                'service_time' => '09:15:00',
                'pool_gallons' => 50000,
                'fac' => 3.0,
                'cc' => 0.0,
                'ph' => 7.6,
                'alkalinity' => 130,
                'calcium' => 280,
                'salt' => null,
                'cya' => 40,
                'tds' => 900,
                'vacuumed' => true,
                'brushed' => true,
                'skimmed' => true,
                'cleaned_skimmer_basket' => true,
                'cleaned_pump_basket' => true,
                'cleaned_pool_deck' => true,
                'cleaned_filter_cartridge' => false,
                'backwashed_sand_filter' => true,
                'adjusted_water_level' => true,
                'adjusted_auto_fill' => false,
                'adjusted_pump_timer' => true,
                'adjusted_heater' => false,
                'checked_cover' => true,
                'checked_lights' => true,
                'checked_fountain' => false,
                'checked_heater' => false,
                'chemicals_used' => ['chlorine' => '3 lbs', 'algaecide' => '1 qt'],
                'chemicals_cost' => 45.00,
                'other_services' => ['backwash' => 'Sand filter backwashed'],
                'other_services_cost' => 10.00,
                'total_cost' => 55.00,
                'notes_to_client' => 'Commercial pool service completed. All systems functioning properly. Pool cover inspected.',
                'notes_to_admin' => 'Large commercial pool. All maintenance tasks completed successfully.',
            ],
            [
                'client_id' => $clients->count() > 3 ? $clients[3]->id : $clients->first()->id,
                'location_id' => $locations->count() > 3 ? $locations[3]->id : $locations->first()->id,
                'technician_id' => $technicians->count() > 3 ? $technicians[3]->id : $technicians->first()->id,
                'service_date' => Carbon::now()->subDays(28),
                'service_time' => '14:00:00',
                'pool_gallons' => 22000,
                'fac' => 2.2,
                'cc' => 0.1,
                'ph' => 7.3,
                'alkalinity' => 115,
                'calcium' => 240,
                'salt' => 3000,
                'cya' => 55,
                'tds' => 1100,
                'vacuumed' => true,
                'brushed' => false,
                'skimmed' => true,
                'cleaned_skimmer_basket' => true,
                'cleaned_pump_basket' => false,
                'cleaned_pool_deck' => false,
                'cleaned_filter_cartridge' => false,
                'backwashed_sand_filter' => false,
                'adjusted_water_level' => true,
                'adjusted_auto_fill' => false,
                'adjusted_pump_timer' => false,
                'adjusted_heater' => true,
                'checked_cover' => false,
                'checked_lights' => true,
                'checked_fountain' => false,
                'checked_heater' => true,
                'chemicals_used' => ['salt' => '3 lbs'],
                'chemicals_cost' => 20.00,
                'other_services' => ['heater_check' => 'Heater settings verified'],
                'other_services_cost' => 5.00,
                'total_cost' => 25.00,
                'notes_to_client' => 'Pool chemistry balanced. Heater settings checked and adjusted. Pool is ready for use.',
                'notes_to_admin' => 'Standard service with heater maintenance.',
            ],
            [
                'client_id' => $clients->count() > 4 ? $clients[4]->id : $clients->first()->id,
                'location_id' => $locations->count() > 4 ? $locations[4]->id : $locations->first()->id,
                'technician_id' => $technicians->count() > 4 ? $technicians[4]->id : $technicians->first()->id,
                'service_date' => Carbon::now()->subDays(35),
                'service_time' => '08:45:00',
                'pool_gallons' => 15000,
                'fac' => 2.8,
                'cc' => 0.0,
                'ph' => 7.5,
                'alkalinity' => 125,
                'calcium' => 260,
                'salt' => 3400,
                'cya' => 65,
                'tds' => 1300,
                'vacuumed' => true,
                'brushed' => true,
                'skimmed' => true,
                'cleaned_skimmer_basket' => true,
                'cleaned_pump_basket' => true,
                'cleaned_pool_deck' => true,
                'cleaned_filter_cartridge' => true,
                'backwashed_sand_filter' => false,
                'adjusted_water_level' => true,
                'adjusted_auto_fill' => true,
                'adjusted_pump_timer' => true,
                'adjusted_heater' => false,
                'checked_cover' => false,
                'checked_lights' => false,
                'checked_fountain' => false,
                'checked_heater' => false,
                'chemicals_used' => ['salt' => '4 lbs', 'stabilizer' => '1 lb'],
                'chemicals_cost' => 30.00,
                'other_services' => ['filter_cleaning' => 'Filter cartridge cleaned'],
                'other_services_cost' => 10.00,
                'total_cost' => 40.00,
                'notes_to_client' => 'Comprehensive pool service completed. All systems checked and maintained.',
                'notes_to_admin' => 'Full service including filter cleaning and timer adjustment.',
            ],
        ];

        foreach ($reportData as $report) {
            Report::create($report);
        }

        $this->command->info('Created ' . count($reportData) . ' sample reports.');
    }
} 