@php
    $brand = $tenant?->brand_color ?: '#0ea5e9';
    $company = $tenant?->name ?? 'RoutePilot';
    $money = fn ($n) => '$' . number_format((float) $n, 2);
    $statusColors = ['paid' => '#059669', 'overdue' => '#dc2626', 'sent' => '#d97706', 'draft' => '#6b7280', 'void' => '#6b7280'];
    $statusColor = $statusColors[$invoice->status] ?? '#6b7280';
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1f2937; font-size: 12px; margin: 0; }
        .bar { height: 6px; background: {{ $brand }}; }
        .wrap { padding: 36px 40px; }
        .head { width: 100%; }
        .head td { vertical-align: top; }
        .company { font-size: 20px; font-weight: bold; color: {{ $brand }}; }
        .muted { color: #6b7280; }
        .title { font-size: 26px; font-weight: bold; text-align: right; }
        .status { display: inline-block; padding: 3px 10px; border-radius: 10px; color: #fff; font-size: 11px; font-weight: bold; text-transform: uppercase; background: {{ $statusColor }}; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 28px; }
        table.items th { text-align: left; border-bottom: 2px solid #e5e7eb; padding: 8px 6px; font-size: 11px; text-transform: uppercase; color: #6b7280; }
        table.items td { padding: 8px 6px; border-bottom: 1px solid #f3f4f6; }
        .right { text-align: right; }
        .totals { width: 240px; float: right; margin-top: 16px; }
        .totals td { padding: 4px 6px; }
        .totals .grand { font-size: 15px; font-weight: bold; border-top: 2px solid #e5e7eb; }
        .due { color: {{ $statusColor }}; font-weight: bold; }
        .foot { margin-top: 60px; font-size: 11px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="bar"></div>
    <div class="wrap">
        <table class="head">
            <tr>
                <td>
                    <div class="company">{{ $company }}</div>
                    @if ($tenant?->primary_domain)<div class="muted">{{ $tenant->primary_domain }}</div>@endif
                </td>
                <td>
                    <div class="title">INVOICE</div>
                    <div class="right muted">{{ $invoice->number }}</div>
                    <div class="right" style="margin-top:6px;"><span class="status">{{ $invoice->status }}</span></div>
                </td>
            </tr>
        </table>

        <table class="head" style="margin-top:28px;">
            <tr>
                <td>
                    <div class="muted">Bill to</div>
                    <div style="font-weight:bold; font-size:14px;">{{ $invoice->customer?->displayName() }}</div>
                </td>
                <td class="right">
                    <div class="muted">Issued: {{ optional($invoice->issued_at)->format('M j, Y') ?? '—' }}</div>
                    <div class="muted">Due: {{ optional($invoice->due_at)->format('M j, Y') ?? '—' }}</div>
                </td>
            </tr>
        </table>

        <table class="items">
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="right">Qty</th>
                    <th class="right">Unit</th>
                    <th class="right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($invoice->lineItems as $line)
                    <tr>
                        <td>{{ $line->description }}</td>
                        <td class="right">{{ rtrim(rtrim(number_format((float) $line->quantity, 2), '0'), '.') }}</td>
                        <td class="right">{{ $money($line->unit_price) }}</td>
                        <td class="right">{{ $money($line->amount) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <table class="totals">
            <tr><td class="muted">Subtotal</td><td class="right">{{ $money($invoice->subtotal) }}</td></tr>
            <tr><td class="muted">Tax</td><td class="right">{{ $money($invoice->tax) }}</td></tr>
            <tr class="grand"><td>Total</td><td class="right">{{ $money($invoice->total) }}</td></tr>
            @if ((float) $invoice->amount_paid > 0)
                <tr><td class="muted">Paid</td><td class="right">−{{ $money($invoice->amount_paid) }}</td></tr>
                <tr><td class="due">Balance due</td><td class="right due">{{ $money($invoice->balance()) }}</td></tr>
            @endif
        </table>

        <div style="clear:both;"></div>
        <div class="foot">Thank you for your business. Generated by {{ $company }} via RoutePilot.</div>
    </div>
</body>
</html>
